const consultarScoreDelClienteResponse = {
    mensaje:"",
    exito:"True",
    respuesta: {
        cve_presolicitud:"",
        primer_nombre:"",
        segundo_nombre:"",
        apellido_paterno:"",
        apellido_materno:"",
        genero:"",
        curp:"",
        rfc:"",
        correo_electronico:"",
        telefono_celular:"",
        estado_nacimiento:"",
        fecha_nacimiento:"14/4/1990 11:45:22 AM.",
        calle:"",
        no_exterior:"",
        no_interior:"",
        cruzamientos:"",
        codigo_postal:"",
        estado:"",
        municipio:"",
        ciudad:"",
        tipo_asentamiento:"",
        asentamiento:"",
        fg_termino_condiciones:1,
        fg_autorizacion:1,
        codigo_sms:"",
        cve_vendedor:"",
        score_circulo:1,
        score_tipo:"",
        estatus_circulo:1 ,
        caja:"",
        cve_sucursal:"",
        fecha_alta:"14/4/2023 11:45:22 AM.",
        id_red_social:1 ,
        usuario_red_social:"",
        cve_categoria:"",
        cve_marca:"",
        cve_producto:"",
        material:"",
        precio_equipo:0.0,
        iva_equipo:0.0,
        precio_equipo_iva:0.0,
        enganche_minimo:0.0,
        enganche_real:0.0,
        plazo_semanal: 1,
        pago_semanal:0.0,
        pago_semanal_capital:0.0,
        pago_semanal_interes:0.0,
        total_financiado:0.0,
        perfil_riesgo:"",
        celular_perfil:"",
        prestamo_perfil:"",
        motocicleta_perfil:"",
        estatus:0,
        fg_modifico_curp:0,
        fg_modifico_rfc:0,
        score: {
            cveSucursal: "",
            folio: "",
            idEmpresa: 1,
            plataforma: "", 
            caja: "",
            fechaNacimiento: "",
            score: 1,
            persona: {
                nombres: "",
                apellidoPaterno: "",
                apellidoMaterno: "",
                fechaNacimiento: "",
                rfc: "",
                curp: "",
                nacionalidad: "",
                domicilio: {
                     direccion: "",
                     coloniaPoblacion: "",
                     delegacionMunicipio: "",
                     ciudad: "",
                     estado: "",
                     cp: "",
                     numeroTelefono: "",
                } 
            },
        },
        fg_valida_ine:0,
        plataforma:"TEST" ,
        plataforma_id:"TESTID",
        estado_plataforma:"ONLINE" ,
        fg_financiamiento_mixto:1,
        id_tipo_financiamiento:1,
        centroSap:"CASE",
        score_final:0,
        celular_aprobado:0,
        prestamo_aprobado:0,
        motocicleta_aprobada:0,
        cve_presolicitud_originacion:"",
        fg_garantia_extendida:0,
        fg_membresia:0,
        revalidacion:false,
        score_telcel:0.0,
        limite_credito:0.0,
        linea_credito:0.0,
        monto_linea_credito:0.0,
        perfil_fraude:"",
        saldo_linea_de_credito:0.0,
        saldo_vencido_linea_de_credito:0.0,
        anexo_presolicitud:{
            cve_presolicitud :"",
            escolaridad :"",
            ocupacion :"",
            lugar_trabajo :"",
            puesto :"",
            estado_civil :"",
            antiguedad_trabajo :0,
            cantidad_dependientes :"",
            ingreso_mensual :0.0,
            antiguedad_estado_civil :"",
            oper_alta :"",
            tipo_domicilio :"",
            antiguedad_domicilio :"",
            telefono_laboral :"",
            referencia_domicilio :""
        },
        detalle_carrito:[
            {
                 cve_presolicitud : "",
                 cve_categoria : "",
                 descripcion_categoria : "",
                 cve_marca : "",
                 descripcion_marca : "",
                 cve_producto : "",
                 descripcion_producto : "",
                 cantidad : 1,
                 precio_equipo : 0.0,
                 iva_equipo : 0.0,
                 precio_equipo_iva : 0.0,
                 enganche_minimo : 0.0,
                 enganche_real : 0.0,
                 plazo_semanal : 12,
                 pago_semanal : 1.0,
                 pago_semanal_capital : 250.50,
                 pago_semanal_interes : 13.78,
                 total_financiado : 2000.00,
                 material : "",
                 overPrice : 1800.00,
                 id_tipo_financiamiento : 1,
                 fg_garantia_extendida : 1,
                 fg_membresia : 1,
                 fg_financiamiento_mixto : 1,
            }
        ],
        fg_evaluado_limite_credito:0,
        fg_white_list:0,
        no_creditos_activos:0,
        no_creditos_permitidos:0,
        latitud_domicilio:0.0,
        longitud_domicilio:0.0,
        fg_busqueda:0,
        nb_cliente:"",
        fg_fallo_api_telcel:0,
        fg_multifinanciamiento_sucursal:0,
        fg_multifinanciamiento_perfil:0,
        excedente_multifinanciamiento:0.0,
        cantidad_multifinanciamiento:0,
        estrategia_white_list:"",
        id_cupon_white_list:0,
        tipoActivo:"",
        cve_solicitud:"",
        originacion:0,
        razon_rechazo:"",
        razon_rechazo_detalle:"",
        fg_datos_actualizados:0,
    },
    contieneObjectoError: "False",
    detalleError: "",
}

const consultarTiposDeCreditoResponse = {
        "mensaje": "", 
        "exito": "True", 
        "respuesta": {
            "redes" : [
                {
                    "id_red_social" : 0,
                    "descripcion" : ""
            }
            ],
            "tiposDeCreditos" : [
                {
                    "cve_categoria" : "",
                    "descripcion_categoria" : "",
                    "cve_marca" : "",
                    "descripcion_marca" : "",
                    "centroSap" : "",
                    "marcas" : [
                        {
                            "cve_marca" : "",
                            "descripcion_marca" : "",
                            "fg_financiamiento_mixto" : false,
                            "modelos" : [
                                {
                                    "cve_presolicitud" : "",
                                    "cve_producto" : "",
                                    "descripcion_producto" : "",
                                    "cve_categoria" : "",
                                    "cve_marca" : "",
                                    "cve_sucursal" : "",
                                    "centroSap" : "",
                                    "material" : "",
                                    "precio_venta" : 0,
                                    "fullPrice" : 0,
                                    "overPrice" : 0,
                                    "existencia" : 0,
                                    "detalle" : [
                                        {
                                            "Pr_Cve_Producto" : "",
                                            "Pr_Descripcion" : "",
                                            "Pr_Descripcion_Corta" : "",
                                            "estatus" : "",
                                            "fg_habilitado" : 0,
                                            "Sr_Cve_Serie" : "",
                                            "Sr_Cve_Sucursal" : "",
                                            "centroSap" : "",
                                            "material" : "",
                                            "cve_marca" : "",
                                            "id_tipo_financiamiento" : 0,
                                        }
                                    ],
                                    "tipoDeFinanciamiento" : "",
                                    "id_tipo_financiamiento" : 0,
                                    "score" : "",
                                    "fg_financiamiento_mixto" : false,
                                    "fg_recompra" : 0,
                                    "perfil" : "",
                                }
                            ],
                        }
                    ],
                    "perfil" : "",
                    "tipoLlenado" : "",
                    "tipoDeFinanciamiento" : "",
                    "celular_aprobado" : 0,
                    "prestamo_aprobado" : 0,
                    "fg_financiamiento_mixto" : false,
                    "score" : 0,
                }
            ],
            "se_envia_sms" : 0,
            "se_activa_emailage" : false,
            "se_valida_mati_full" : false,
            "nombre_evento_consulta_mati_light" : "",
            "se_valida_score" : false,
            "ambiente_mati" : "",
            "cliente_mati" : "",
            "flujo_mati" : "",
            "ciclos_busqueda_mati" : 0,
            "tiempo_entre_ciclos_busqueda_mati" : 0,
            "ambiente_mati_efectivo" : "",
            "cliente_mati_efectivo" : "",
            "flujo_mati_efectivo" : "",
            "terminos_credito_telefono" : "",
            "terminos_credito_efectivo" : "",
            "aceptacion_terminos_credito_telefono" : "",
            "aceptacion_terminos_credito_efectivo" : "",
            "no_reintentos_envio_sms" : 0,
            "tiempo_reintento_envio_sms" : 0,
            "mensaje_error" : "",
            "terminos_garantia_extendida" : "",
            "terminos_membresia" : "",
            "configuracion_multifinanciamiento" : [
                {
                    "tipo_compra" : "",
                    "perfil" : "",
                    "es_recompra" : 0,
                    "es_multifinanciamiento" : 0,
                    "excedente_maximo" : 0,
                    "no_creditos_permitidos" : 0,
        
                }
            ],
        }, 
        "contieneObjectoError": "False", 
        "detalleError": ""

};

const consultarCalculadoraResponse = {
    "mensaje": "", 
    "exito": "True", 
    "respuesta": {
        "cve_categoria" : "",
        "descripcion_categoria ": "",
        "cve_marca" : "",
        "descripcion_marca" : "",
        "cve_producto" : "",
        "descripcion_producto" : "",
        "precio_equipo" : 0,
        "iva_equipo" : 0,
        "precio_equipo_iva" : 0,
        "plazo" : 0,
        "enganche_minimo" : 0,
        "enganche" : 0,
        "pago_semanal" : 0,
        "pago_semanal_capital" : 0,
        "pago_semanal_interes" : 0,
        "total_financiado" : 0,
        "perfil" : "",
        "caja" : "",
        "score_circulo" : 0,
        "plazos" : [ 
            {
                "plazo" : 0,
                "enganche" : 0,
                "enganche_minimo" : 0,
                "pago_semanal" : 0,
                "pago_semanal_capital" : 0,
                "pago_semanal_interes" : 0,
                "total_financiado" : 0,
                "meses" : ""
            }],
        "cve_presolicitud" : "",
        "fullPrice" : 0,
        "overPrice" : 0,
        "material" : "",
        "meses" : "",
        "cve_sucursal" : "",
        "centroSap": "",
        "id_tipo_financiamiento" : 0,
        "fg_validar_caja_sap_prestamo" : 0,
        "centro_sap_sapi" : "",
        "limite_credito_permitido_para_prestamos" : 0,
        "fg_financiamiento_mixto" : 0,
        "fg_garantia_extendida" : 0,
        "fg_membresia" : 0
    }, 
    "contieneObjectoError": "False", 
    "detalleError": ""
};

const consultarModeloResponse = {
    "mensaje": "", 
    "exito": "True", 
    "respuesta": [{
        "cve_presolicitud" : "",
        "cve_producto" : "",
        "descripcion_producto" : "",
        "cve_categoria" : "",
        "cve_marca" : "",
        "cve_sucursal" : "",
        "centroSap" : "",
        "material" : "",
        "precio_venta" : 0,
        "fullPrice" : 0,
        "overPrice" : 0,
        "existencia" : 0,
        "detalle" : [{
            "Pr_Cve_Producto" : "",
            "Pr_Descripcion" : "",
            "Pr_Descripcion_Corta" : "",
            "estatus" : "",
            "fg_habilitado" : 0,
            "Sr_Cve_Serie" : "",
            "Sr_Cve_Sucursal" : "",
            "centroSap" : "",
            "material" : "",
            "cve_marca" : "",
            "id_tipo_financiamiento" : 0
        }],
        "tipoDeFinanciamiento" : "",
        "id_tipo_financiamiento" : 0,
        "score" : "",
        "fg_financiamiento_mixto" : false,
        "fg_recompra" : 0,
        "perfil" : "",
    }], 
    "contieneObjectoError": "False", 
    "detalleError": ""
};

const procesarCarritoDeCompraResponse = {
    mensaje: "", 
    exito: "True", 
    respuesta: [{
        cve_solicitud :"",
        cve_contrato :"",
        cve_cliente :"",
        cve_sucursal :"",
        centro_sap :"",
        cve_vendedor :"",
        cve_categoria :"",
        descripcion_categoria :"",
        cve_marca :"",
        descripcion_marca :"",
        cve_producto :"",
        descripcion_producto :"",
        precio_equipo :0.0,
        iva_equipo :0.0,
        precio_equipo_iva :0.0,
        enganche_minimo :0.0,
        enganche_real :0.0,
        plazo_semanal :0,
        pago_semanal :0.0,
        pago_semanal_capital :0.0,
        pago_semanal_interes :0.0,
        total_financiado :0.0,
        fg_terminos_condiciones :0,
        fg_autorizacion :0,
        codigo_sms :"",
        score_circulo :0,
        estatus_circulo :0,
        perfil_riesgo :"",
        estatus :0,
        primer_nombre :"",
        segundo_nombre :"",
        apellido_paterno :"",
        apellido_materno :"",
        nombre_completo :"",
        genero :"",
        curp :"",
        rfc :"",
        correo_electronico :"",
        telefono_celular :"",
        telefono_fijo :"",
        estado_nacimiento :"",
        fecha_nacimiento :null,
        estado_civil :"",
        antiguedad_estado_civil :"",
        calle :"",
        no_exterior :"",
        no_interior :"",
        cruzamientos :"",
        codigo_postal :"",
        estado :"",
        municipio :"",
        ciudad :"",
        tipo_asentamiento :"",
        asentamiento :"",
        tipo_domicilio :"",
        antiguedad_domicilio :"",
        referencia_domicilio :"",
        escolaridad :"",
        ocupacion :"",
        lugar_trabajo :"",
        puesto :"",
        telefono_laboral : "",
        ingreso_mensual :0.0,
        antiguedad_trabajo :0,
        cantidad_dependientes :"",
        fg_tarjeta_debito :0,
        referencia_tarjeta_debito :"",
        fg_tarjeta_credito :0,
        referencia_tarjeta_credito :"",
        id_parentesco :0,
        descripcion_parentesco :"",
        nombre_referencia :"",
        apellido_paterno_referencia :"",
        apellido_materno_referencia :"",
        id_horario_contacto :0,
        horario_referencia :"",
        telefono_referencia :"",
        fg_contactar_whatsapp :0,
        orden :0,
        imei :"",
        caja :"",
        id_tipo_financiamiento :0,
        fg_recompra :0,
        fg_cliente_interno :0,
        fg_membresia :0,
        fecha_alta :"22/4/2023 11:52 AM",
        contactoPreferente :"",
        referencias :[{
            orden : 1,
            cve_solicitud :"",
            nombre_referencia :"",
            nombre :"",
            apellido_paterno :"",
            apellido_materno :"",
            curp_cliente :"",
            telefono_referencia :"",
            id_parentesco :1,
            id_horario_contacto :1,
            fg_contactar_whatsapp :1
            }
        ],
        contrato :
                {
                        cve_solicitud :"",
                        cve_contrato :"",
                        cve_vendedor :"",
                        caja :"",
                        cve_sucursal :"",
                        folio_registro_intranet :"",
                        folio_registro_intranet_largo :"",
                },

        paso :"",
        nombre :"",
        anexo_presolicitud : {
                cve_presolicitud :"",
                escolaridad :"",
                ocupacion :"",
                lugar_trabajo :"",
                puesto :"",
                estado_civil :"",
                antiguedad_trabajo :0,
                cantidad_dependientes :"",
                ingreso_mensual :0.0,
                antiguedad_estado_civil :"",
                oper_alta :"",
                tipo_domicilio :"",
                antiguedad_domicilio :"",
                telefono_laboral :"",
                referencia_domicilio :""
        },
        revalidacion :true,
        verificado :false,
        cve_presolicitud :"",
        id_cupon_white_list :0
        }
    ], 
    contieneObjectoError: "False", 
    detalleError: ""
};

module.exports = { 
    consultarScoreDelClienteResponse,
    consultarTiposDeCreditoResponse, 
    consultarCalculadoraResponse, 
    consultarCalculadoraResponse, 
    consultarModeloResponse, 
    procesarCarritoDeCompraResponse 
};